[package]
name = "updated_guessing_game"
version = "0.1.0"
edition = "2021"
author = "Sayf Al-Deen Hassouneh"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
colored = "2.1.0"
